# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'e-life' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for e-life
    pod 'lottie-ios'
    pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'SwiftyJSON', '~> 5.0'
    pod 'SVProgressHUD', '~> 2.2'
end
